### PR TITLE
Fix #63: The week_start is different from WakaTime

### PR DESCRIPTION
**Pull request by ryul1206**
Thank you very much for allowing PR.
This PR is to the master branch since I couldn't find any development branch.

### CODE REVIEW

**Review by joe733 — APPROVED** [review]
Thanks for the PR!

**Comment by athul** [comment]
Hey, could you explain what this PR actually does? I'm a tad confused 😅

**Comment by ryul1206** [comment]
Hello @athul ,
this action uses one-week information via `last_7_days`.
In the current code, there is 7 days difference between `week_start` and `week_end`.

https://github.com/athul/waka-readme/blob/30896489cb3b2923d864415ef5fca780c30415d2/main.py#L30

However, I think the interval between the start and end of a week is only 6 days.
`[mon]-1-[tue]-2-[wed]-3-[thu]-4-[fri]-5-[sat]-6-[sun]`

So, for example, Monday is `sunday - datetime.timedelta(days=6)`. As I mentioned in #63, my Wakatime information and the current waka-readme title are not the same, so I suggest this PR.

**Comment by joe733** [comment]
@athul, may I add https://github.com/athul/waka-readme/issues/33 asks about a bi-weekly status, if we allow `timedelta` to be changed by workflow configuration, will we be able to get statistics within a custom time slice?

**Comment by athul** [comment]
@ryul1206 That makes sense 👍 . Thanks for the Response. @joe733 As mentioned in #33 The API doesn't support it 😞 

If everything fine, I'll move to merging this

**Review by athul — APPROVED** [review]
LGTM

**Comment by joe733** [comment]
yup, good to go 👍🏻

**Pull request merged**
