### PR TITLE
Add support for parametrized blocks

### PR DESCRIPTION
**Pull request by malkam03**
- Modify action to support input of block string
- Modify make graph function to support parametrized blocks
- Add tests for parametrized blocks
- Update README with new issue
- Fix some format errors and typos

### CODE REVIEW

**Comment by malkam03** [comment]
Hello @athul , sorry if this is not the format you're using for the project but I didn't found any contributing.mg or guidelines for this. This PR contains a feature that I wanted to add for my readme and think that maybe is helpful for others. Also, there're some changes to the format of a couple of files that the lint plugin that I have for my code editor changed automatically. Please tell me what do you think of this, if you find any value on it and/or if you have any suggestion or change.

**Comment by malkam03** [comment]
Also, for an example of this action working, you can check my [profile readme](https://github.com/malkam03/malkam03).

**Review by athul — APPROVED** [review]
LGTM

**Comment by athul** [comment]
Hey @malkam03 . This is pretty cool. Sorry for the late reply, was stuck at something else. Merging this :tada:

**Comment by nelson6e65** [comment]
Amazing!

**Pull request merged**
