### PR TITLE
add new test cases, add test_generate_new_readme

### PR DESCRIPTION
**Pull request by siddharth2016**
Added test_generate_new_readme, let me know if needed any changes or need to add more scenarios. Thanks !

### CODE REVIEW

**Comment by siddharth2016** [comment]
Added test_decode_readme, let me know if needed any changes or need to add more scenarios. Thanks !

**Review by joe733 — APPROVED** [review]
Thanks!

**Review by athul — APPROVED** [review]
Thank you for the PR.

**Comment by athul** [comment]
But Could you remove the first 3 commits?

You can go to your fork and pull the latest commit to your master branch and cherry-pick these commits to your branch. That way we could get the commits you pushed.

`$ git pull master --set-upstream https://github.com/athul/waka-readme.git` You can use this command to get the latest commits from the master to your fork's clone

https://athul.github.io/notes/posts/git-cherry.html

Here is something to get you

**Comment by siddharth2016** [comment]
> But Could you remove the first 3 commits?
> 
> You can go to your fork and pull the latest commit to your master branch and cherry-pick these commits to your branch. That way we could get the commits you pushed.
> 
> `$ git pull master --set-upstream https://github.com/athul/waka-readme.git` You can use this command to get the latest commits from the master to your fork's clone
> 
> https://athul.github.io/notes/posts/git-cherry.html
> 
> Here is something to get you

Hi
Can you please elaborate ? I didn't get what you want me to do ? Sorry, i am new to this kind of thing !

**Comment by siddharth2016** [comment]
I will be creating a new pull request, please approve that and merge, thanks !

**Pull request closed without merging**
