### PR TITLE
add new test cases, add test_generate_new_readme, add test_decode_readme

### PR DESCRIPTION
**Pull request by siddharth2016**
Sorry again, creating PR, please let me know what is the issue, thanks !

### CODE REVIEW

**Comment by athul** [comment]
Hey don't worry. I'll walk you through it by tommorow eve. This is how we learn right😃

**Comment by siddharth2016** [comment]
Thank you so much, will not create new PR further for this commit.

**Comment by siddharth2016** [comment]
Hi
Shall i add new test cases in add_test_cases branch ? It seems i have already done couple of PRs to update my forked master branch. So only add_test_cases is not up-to-date with master and can include my commits.
Please suggest whenever you get time. Thanks !

**Comment by athul** [comment]
Hey @siddharth2016 I'm sorry for responding slowly. Is it possible that you can create a new fresh fork of this and add these commits there? Or else you can do the following

---

- Go to your local clone
- run `$ git log` and get the commit hashes for your commit . Those would be `d142c0e` and `a72218c`.
- checkout to master
- run `$ git pull master --set-upstream https://github.com/athul/waka-readme.git` to update to the latest commits
- Once the pull is done, checkout to your development branch, ie `sid_test_cases`
- run `$ git reset --hard master` to make that branch in par with master
- run `$ git cherry-pick d142c0e a72218c`. This will attach the commits to the `sid_test_cases` branch again after resetting
- Force Push with `$ git push origin sid_test_cases --force`
- Profit :tada:

**Comment by joe733** [comment]
> Hey @siddharth2016 I'm sorry for responding slowly. Is it possible that you can create a new fresh fork of this and add these commits there? Or else you can do the following
> 
>     * Go to your local clone
> 
>     * run `$ git log` and get the commit hashes for your commit . Those would be `d142c0e` and `a72218c`.
> 
>     * checkout to master
> 
>     * run `$ git pull master --set-upstream https://github.com/athul/waka-readme.git` to update to the latest commits
> 
>     * Once the pull is done, checkout to your development branch, ie `sid_test_cases`
> 
>     * run `$ git reset --hard master` to make that branch in par with master
> 
>     * run `$ git cherry-pick d142c0e a72218c`. This will attach the commits to the `sid_test_cases` branch again after resetting
> 
>     * Force Push with `$ git push origin sid_test_cases --force`
> 
>     * Profit tada

I learned something.. :)

**Comment by siddharth2016** [comment]
> Hey @siddharth2016 I'm sorry for responding slowly. Is it possible that you can create a new fresh fork of this and add these commits there? Or else you can do the following
> 
> * Go to your local clone
> * run `$ git log` and get the commit hashes for your commit . Those would be `d142c0e` and `a72218c`.
> * checkout to master
> * run `$ git pull master --set-upstream https://github.com/athul/waka-readme.git` to update to the latest commits
> * Once the pull is done, checkout to your development branch, ie `sid_test_cases`
> * run `$ git reset --hard master` to make that branch in par with master
> * run `$ git cherry-pick d142c0e a72218c`. This will attach the commits to the `sid_test_cases` branch again after resetting
> * Force Push with `$ git push origin sid_test_cases --force`
> * Profit 🎉

Created new fork and added my commits there. With git pull master command, i was getting this error:

fatal: Invalid refspec 'https://github.com/athul/waka-readme.git'

**Comment by athul** [comment]
> > Hey @siddharth2016 I'm sorry for responding slowly. Is it possible that you can create a new fresh fork of this and add these commits there? Or else you can do the following
> > 
> > * Go to your local clone
> > * run `$ git log` and get the commit hashes for your commit . Those would be `d142c0e` and `a72218c`.
> > * checkout to master
> > * run `$ git pull master --set-upstream https://github.com/athul/waka-readme.git` to update to the latest commits
> > * Once the pull is done, checkout to your development branch, ie `sid_test_cases`
> > * run `$ git reset --hard master` to make that branch in par with master
> > * run `$ git cherry-pick d142c0e a72218c`. This will attach the commits to the `sid_test_cases` branch again after resetting
> > * Force Push with `$ git push origin sid_test_cases --force`
> > * Profit 🎉
> 
> Created new fork and added my commits there. With git pull master command, i was getting this error:
> 
> fatal: Invalid refspec 'https://github.com/athul/waka-readme.git'

remove the `master` in `$git pull`

**Pull request closed without merging**
