### PR TITLE
feat: Added week #number to dev metrics

### PR DESCRIPTION
**Pull request by joe733**
### `main.py`

- Added week number:
```python
08. import datetime

...

16. this_week = datetime.datetime.now().strftime('%W')

...

24.     return '```text\n'+'Week #'+this_week+'\n'+data+'\n```'
```
- Applied [`snake_case`](https://en.wikipedia.org/wiki/Snake_case) at some places.
- Double quotes for f-strings. Rest got single quotes. `¯\_(ツ)_/¯`

### `README.md`

- Some linting fixes and a typo.

### CODE REVIEW

**Comment by athul** [comment]
Hey, Is it possible to show the screenshot or an example of the output?

**Comment by joe733** [comment]
I wish to, but I haven't yet set up docker on my system. But here's the expected output.

```text
Week #29
Python      38 mins             ████████████░░░░░░░░░░░░░   50.15 
Markdown    29 mins             █████████░░░░░░░░░░░░░░░░   38.79 
HTML        8 mins              ██░░░░░░░░░░░░░░░░░░░░░░░   10.68 
Other       0 secs              ░░░░░░░░░░░░░░░░░░░░░░░░░   0.38
```

I thought to add something like this too...

```text
Week #29 : Jul 12 - 18
Python      38 mins             ████████████░░░░░░░░░░░░░   50.15 
Markdown    29 mins             █████████░░░░░░░░░░░░░░░░   38.79 
HTML        8 mins              ██░░░░░░░░░░░░░░░░░░░░░░░   10.68 
Other       0 secs              ░░░░░░░░░░░░░░░░░░░░░░░░░   0.38
```
but only after testing each change.

**Comment by athul** [comment]
I like this. Why not add it to the Heading Section of the Stats. Currently it's upto the user to add a heading, Maybe we could rewrite that and use the script to update the Heading everyday

**Comment by athul** [comment]
Screen Shot 2020-07-15 at 1 46 52 PM

This one the "Weekly Development Breakdown" is the Header

**Comment by joe733** [comment]
Yea, but... what if the user wants a custom header?

Screenshot from 2020-07-15 14-34-24

 Can we provide such an option from within the comment:

```
<!--OPTIONAL_HEADER-->
<!--START_SECTION:waka-->
<!--END_SECTION:waka-->
```

where the default can be set as: **📊 Weekly Development Breakdown** or is there a better way?

---

Probably add a `%` too at the end?

**Comment by athul** [comment]
Or Maybe Drop the Header thing. I like the latter one with the week and Month and the `%` sign too.

**Comment by joe733** [comment]
> Or Maybe Drop the Header thing. I like the latter one with the week and Month and the `%` sign too.

Alright!

**Comment by joe733** [comment]
Done, added both week span and `%` symbol. It should work (last one did). Is it okay... can you tag this as next release?

**Comment by joe733** [comment]
Yep! It's working.

Screenshot from 2020-07-17 09-51-47

**Comment by athul** [comment]
Cool. Thanks Man

**Comment by rajitbanerjee** [comment]
Is there a way to change the header? It's actually not accurate. The Waka Time API returns metrics from the last 7 days from the current date, and not according to weeks of the year. @joe733 could you please modify the code so that the header displays the last 7 days: e.g. running the workflow on July 17 should return the header "Week: July 9 - July 16". I'm not sure what to do about the week number. 
image

**Pull request merged**
