### PR TITLE
Overhaulin'

### PR DESCRIPTION
**Pull request by joe733**
... wait for it...

### CODE REVIEW

**Comment by athul** [comment]
🚀

**Comment by athul** [comment]
Also kick travis.yml out and add GitHub actions in place 🙈

**Comment by joe733** [comment]
Okay.. here goes..

### the cause ...

- The source code has be re-written, of-course drawing inspiration from the previous versions, but has improved significantly, in terms of readability and reliability... and a few other +ve attributes that you can roll off your sleeve.
- The test coverage isn't 100%, which means automated tests currently do not test each and every function separately - yes there's room.. but may require some slight function parameter modification.
- Last Travis CI test on this PR passed, so the similar GitHub actions `testing.yml` (to test WakaReadme) should too.
- @athul I've not be able to test the `dockerfile` (not sure how to do it), hopefully it'll work fine. But I can test though, if this PR gets merged.


### ... and the effect

First, to the WakaReadme action **users**:

- You need not change anything.  But maybe you can consider [this](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) tip, checkout `README.md`.

To the WakaReadme **developer/contributors**:

- We've a guide-ish for you. Checkout `CONTRIBUTING.md`.
- Not yet on Python 3.10, huh? [`asdf`](https://github.com/asdf-vm/asdf) or [`pyenv`](https://github.com/pyenv/pyenv) can help you out. My un-biased choice is `asdf` 😉 
- WhereTH is `requirements.txt`?!
    - We moved on to [Poetry](https://python-poetry.org/) 🙈. 
    - Fortunately `pyproject.toml` as in [PEP 621](https://www.python.org/dev/peps/pep-0621/), contains the minimum version of each dependency, from which you can create `requirements.txt`, but you probably don't wanna do that... so Poetry can generate it for you! Give Poetry a try, you might like it 😃 
- Now you can put environment variables with secrets in a `.env` file in the project root.

**Comment by joe733** [comment]
> Damn @joe733 . I'll give a review by night, a bit tied upsee_no_evilsee_no_evil.

Sure no problem!

> Also to check of everything works, maybe point to the branch in the GitHub actions' yml file of your personal profile readme repo or a dummy repo with the waka-readme action.

Yup, was just doing that..

**Comment by joe733** [comment]
There's a small issue with the docker file. Not yet sure why. Some discussion took place here: https://github.com/python-poetry/poetry/discussions/1879#discussioncomment-2255728

**Comment by joe733** [comment]
Finally after eleven tries! 🥲 

My bad, should've read the docs.. [WORKDIR in GitHub Actions](https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#workdir) is kind of preset. `COPY` to `/` (and not `./`) simply works. Sorry for so many forced pushes and for the generated email spam 😬 

- [X] Tested `Dockerfile` | [last successful run](https://github.com/joe733/joe733/runs/5344425495?check_suite_focus=true)

**Comment by athul** [comment]
Is it up for merge?

**Comment by joe733** [comment]
Yup, I think so!

**Comment by athul** [comment]
+1 on the Logs too. Too fking awesome 🔥

**Comment by athul** [comment]
Screen Shot 2022-02-27 at 4 17 48 PM

Worked well for me 💯

**Pull request merged**
